[0m06:27:18.315048 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020819CADFD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020817C56490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002081A961590>]}


============================== 06:27:18.321461 | f25a3057-d12a-4b74-a3fc-6497247a60b6 ==============================
[0m06:27:18.321461 [info ] [MainThread]: Running with dbt=1.9.4
[0m06:27:18.322526 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\BATISTA\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init ETL_case_NBA', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m06:27:18.334802 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/BATISTA/.dbt')}
[0m06:27:18.335481 [info ] [MainThread]: Creating dbt configuration folder at 
[0m06:27:18.337993 [debug] [MainThread]: Starter project path: C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\include\starter_project
[0m06:27:18.347730 [info ] [MainThread]: 
Your new dbt project "ETL_case_NBA" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m06:27:18.348739 [info ] [MainThread]: Setting up your profile.
[0m06:27:34.185477 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m06:27:34.185955 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m06:27:34.186246 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m06:37:06.719523 [error] [MainThread]: Encountered an error:

[0m06:37:06.722856 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\task\init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\task\init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\task\init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\task\init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ~~~~~~~~~~~~^
        text, default=default, hide_input=hide_input, type=type
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m06:37:06.724999 [debug] [MainThread]: Command `dbt init` failed at 06:37:06.724812 after 588.53 seconds
[0m06:37:06.725428 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000208360936F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000208360BB890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020835FDF460>]}
[0m06:37:06.725852 [debug] [MainThread]: Flushing usage events
[0m06:37:07.583970 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m06:38:03.778790 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000214ECA1DFD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000214EA9DA490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000214ED6C1590>]}


============================== 06:38:03.782457 | 9ed30538-6b2d-43e3-90c2-58876f3bf5e3 ==============================
[0m06:38:03.782457 [info ] [MainThread]: Running with dbt=1.9.4
[0m06:38:03.783168 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\BATISTA\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init ETL_case_NBA', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m06:38:03.794419 [info ] [MainThread]: A project called ETL_case_NBA already exists here.
[0m06:38:03.795432 [debug] [MainThread]: Command `dbt init` succeeded at 06:38:03.795280 after 0.18 seconds
[0m06:38:03.795836 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000214EDC083E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000214EDBE72F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000214ED9C7350>]}
[0m06:38:03.796252 [debug] [MainThread]: Flushing usage events
[0m06:38:04.435867 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m06:38:19.144415 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014272D01FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014270CBA490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000142739A1590>]}


============================== 06:38:19.148332 | 0c8bc390-5139-4342-899c-64a236be9444 ==============================
[0m06:38:19.148332 [info ] [MainThread]: Running with dbt=1.9.4
[0m06:38:19.149567 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\BATISTA\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init ETL_case_NBA', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m06:38:19.162288 [debug] [MainThread]: Starter project path: C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\include\starter_project
[0m06:38:19.176985 [info ] [MainThread]: 
Your new dbt project "ETL_case_NBA" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m06:38:19.177807 [info ] [MainThread]: Setting up your profile.
[0m06:38:22.723152 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m06:38:22.723582 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m06:38:22.723844 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m06:53:02.611793 [error] [MainThread]: Encountered an error:

[0m06:53:02.615025 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\task\init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\task\init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\task\init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\task\init.py", line 113, in generate_target_from_input
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "C:\Users\BATISTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m06:53:02.616950 [debug] [MainThread]: Command `dbt init` failed at 06:53:02.616757 after 883.57 seconds
[0m06:53:02.617449 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000142104DB6F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000142104FB890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001421041F460>]}
[0m06:53:02.617870 [debug] [MainThread]: Flushing usage events
[0m06:53:03.431302 [debug] [MainThread]: An error was encountered while trying to flush usage events
